[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
fuzz = { runs = 10_000 }
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@prb/test/=lib/prb-test/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/',
    '@chainlink-ccip/=lib/ccip/contracts/'
]
solc = '0.8.19'

[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
optimismGoerli = "${OPTIMISM_GOERLI_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
arbitrumTestnet = "${ARBITRUM_TESTNET_RPC_URL}"
polygonMumbai = "${POLYGON_MUMBAI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
